package frame;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * Kelas ini adalah representasi dari frame utama untuk admin.
 * Kelas ini mengatur tata letak dan fungsi dari menu utama admin aplikasi.
 * Menu yang tersedia termasuk manajemen member, pembayaran, logout, dan keluar.
 * Frame ini juga mengelola koneksi database untuk interaksi dengan data.
 * 
 * @author Fauzi
 */
public class AdminFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public AdminFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Update_Delete_Member = new javax.swing.JButton();
        Payment = new javax.swing.JLabel();
        jLabelWellcome = new javax.swing.JLabel();
        ListOfMember = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 118, 221));

        Update_Delete_Member.setBackground(new java.awt.Color(0, 118, 221));
        Update_Delete_Member.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Update_Delete_Member.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update & delete member.png"))); // NOI18N
        Update_Delete_Member.setText("Update&Delete Member");
        Update_Delete_Member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_Delete_MemberActionPerformed(evt);
            }
        });

        Payment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Payment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/payment.png"))); // NOI18N
        Payment.setText("Payment");
        Payment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PaymentMousePressed(evt);
            }
        });

        jLabelWellcome.setFont(new java.awt.Font("Bahnschrift", 1, 90)); // NOI18N
        jLabelWellcome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelWellcome.setText("WELCOME");

        ListOfMember.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ListOfMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/list of members.png"))); // NOI18N
        ListOfMember.setText("List Of Member");
        ListOfMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ListOfMemberMousePressed(evt);
            }
        });

        Logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        Logout.setText("Logout");
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LogoutMousePressed(evt);
            }
        });

        Exit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        Exit.setText("Exit");
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ExitMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/new member.png"))); // NOI18N
        jLabel2.setText("New Member");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ListOfMember)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Payment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Update_Delete_Member)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Logout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Exit)
                .addGap(13, 13, 13))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(474, Short.MAX_VALUE)
                .addComponent(jLabelWellcome)
                .addGap(452, 452, 452))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ListOfMember, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Payment, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Update_Delete_Member, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(272, 272, 272)
                .addComponent(jLabelWellcome)
                .addGap(0, 330, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1382, 776));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private Connection connect = null;
    private JDialog jDialog = new JDialog();
    
    /**
     * Mengatur koneksi database untuk digunakan dalam kelas ini.
     * 
     * @param connect Objek Connection yang digunakan untuk koneksi database.
     */
    public void setCon(Connection connect){
        this.connect = connect;
    }
    
    /**
     * Mengatur dialog yang digunakan dalam kelas ini.
     * 
     * @param jDialog Objek JDialog yang digunakan untuk dialog.
     */
    public void setDialog(JDialog jDialog){
        this.jDialog = jDialog;
    }
    
    /**
     * Mengembalikan objek Connection yang digunakan dalam kelas ini.
     * 
     * @return Objek Connection yang digunakan untuk koneksi database.
     */
    public Connection getCon(){
        return connect;
    }
    
    /**
     * Mengembalikan objek JDialog yang digunakan dalam kelas ini.
     * 
     * @return Objek JDialog yang digunakan untuk dialog.
     */
    public JDialog getjDialog(){
        return jDialog;
    }
    
    /**
     * Menangani aksi ketika tombol "Update&Delete Member" ditekan.
     * Membuka frame baru untuk mengupdate atau menghapus member.
     * 
     * @param evt Event aksi yang terjadi.
     */
    private void Update_Delete_MemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_Delete_MemberActionPerformed
        // TODO add your handling code here:
        new UpdateDeleteMember().setVisible(true);
    }//GEN-LAST:event_Update_Delete_MemberActionPerformed

    /**
     * Menangani aksi ketika label "List Of Member" ditekan.
     * Membuka frame baru untuk menampilkan daftar member.
     * 
     * @param evt Event mouse yang terjadi.
     */
    private void ListOfMemberMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListOfMemberMousePressed
        // TODO add your handling code here:
        new FrameListMember().setVisible(true);
    }//GEN-LAST:event_ListOfMemberMousePressed

    /**
     * Menangani aksi ketika label "Payment" ditekan.
     * Membuka frame baru untuk melakukan pembayaran.
     * 
     * @param evt Event mouse yang terjadi.
     */
    private void PaymentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaymentMousePressed
        // TODO add your handling code here:
        new Payment().setVisible(true);
    }//GEN-LAST:event_PaymentMousePressed

    /**
     * Menangani aksi ketika label "Logout" ditekan.
     * Menutup frame ini dan membuka frame login.
     * 
     * @param evt Event mouse yang terjadi.
     */
    private void LogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMousePressed
        // TODO add your handling code here:
        new LoginFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutMousePressed

    /**
     * Menangani aksi ketika label "Exit" ditekan.
     * Menutup aplikasi.
     * 
     * @param evt Event mouse yang terjadi.
     */
    private void ExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitMousePressed

    /**
     * Menangani aksi ketika label "New Member" ditekan.
     * Membuka frame baru untuk menambahkan member baru.
     * 
     * @param evt Event mouse yang terjadi.
     */
    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // TODO add your handling code here:
        new NewMember().setVisible(true);
    }//GEN-LAST:event_jLabel2MousePressed

    private void membershipButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel ListOfMember;
    private javax.swing.JLabel Logout;
    private javax.swing.JLabel Payment;
    private javax.swing.JButton Update_Delete_Member;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelWellcome;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
