/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JFrame;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.text.SimpleDateFormat;

/**
 * Kelas NewMember adalah formulir untuk mendaftarkan member baru dengan mengisi informasi yang diperlukan.
 * Kelas ini mengimplementasikan antarmuka Reset untuk mereset form.
 * Ini juga mencakup pembuatan ID unik, penulisan dan pembacaan ID terakhir dari file, dan validasi data sebelum disimpan ke database.
 * 
 * @author rifar
 */
interface Reset{
    /**
     * Metode untuk mereset nilai-nilai dalam form.
     */
    void resetForm();
}

public class NewMember extends javax.swing.JFrame implements Reset{

    /**
     * Creates new form NewMember
     */
    
    private Connection connect = null; // Koneksi ke database
    private static int unique_id; // ID unik untuk setiap member baru
    
    // Path untuk menyimpan file ID unik
    Path currentRelativePath = Paths.get("");
    String s = currentRelativePath.toAbsolutePath().toString();
    private final String ID_FILE_PATH = s + "\\src\\frame\\unik_id.txt";
    
    /**
     * Konstruktor untuk membuat objek NewMember baru.
     * Menginisialisasi komponen GUI dan menampilkan ID unik terakhir yang digunakan.
     */
    public NewMember() {
        initComponents();
        unique_id = readLastUsedID();
        displayUniqueId();
    }
    
    /**
     * Konstruktor alternatif untuk membuat objek NewMember baru dengan parameter khusus.
     * @param unique_id ID unik yang diteruskan
     * @param ID_FILE_PATH Path file yang menyimpan ID unik
     */
    public NewMember(int unique_id, String ID_FILE_PATH){
        unique_id = this.unique_id;
        ID_FILE_PATH = this.ID_FILE_PATH;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fieldName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fieldNo_hp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fieldEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fieldGender = new javax.swing.JComboBox<>();
        btnSimpanData = new javax.swing.JButton();
        btnResetData = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        member_id = new javax.swing.JTextField();
        gymTime = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        bayaran = new javax.swing.JTextField();
        jDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(175, 100));
        setResizable(false);

        jPanel1.setForeground(new java.awt.Color(0, 118, 221));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 118, 221));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/new member.png"))); // NOI18N
        jLabel2.setText("New Member");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 118, 221));
        jLabel5.setText("Name:");

        fieldName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fieldName.setForeground(new java.awt.Color(0, 118, 221));
        fieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNameActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 118, 221));
        jLabel6.setText("Mobile Number:");

        fieldNo_hp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fieldNo_hp.setForeground(new java.awt.Color(0, 118, 221));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 118, 221));
        jLabel7.setText("Email:");

        fieldEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fieldEmail.setForeground(new java.awt.Color(0, 118, 221));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 118, 221));
        jLabel8.setText("Gender:");

        fieldGender.setBackground(new java.awt.Color(204, 204, 204));
        fieldGender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fieldGender.setForeground(new java.awt.Color(0, 118, 221));
        fieldGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose:", "Male", "Female" }));

        btnSimpanData.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSimpanData.setForeground(new java.awt.Color(0, 118, 221));
        btnSimpanData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save.png"))); // NOI18N
        btnSimpanData.setText("Save");
        btnSimpanData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanDataActionPerformed(evt);
            }
        });

        btnResetData.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnResetData.setForeground(new java.awt.Color(0, 118, 221));
        btnResetData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reset.png"))); // NOI18N
        btnResetData.setText("Reset");
        btnResetData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetDataActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 118, 221));
        jLabel9.setText("Gym Time:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 118, 221));
        jLabel10.setText("Unique ID:");

        member_id.setEditable(false);
        member_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        member_id.setForeground(new java.awt.Color(0, 118, 221));
        member_id.setFocusable(false);
        member_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                member_idActionPerformed(evt);
            }
        });

        gymTime.setBackground(new java.awt.Color(204, 204, 204));
        gymTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gymTime.setForeground(new java.awt.Color(0, 118, 221));
        gymTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Package:", "1 Month", "3 Month", "12 Month" }));
        gymTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gymTimeActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 118, 221));
        jLabel11.setText("Birth Date:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 118, 221));
        jLabel12.setText("Amount to pay/month");

        bayaran.setEditable(false);
        bayaran.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bayaran.setForeground(new java.awt.Color(0, 118, 221));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 630, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(fieldName)
                                    .addComponent(jLabel6)
                                    .addComponent(fieldNo_hp)
                                    .addComponent(fieldEmail)
                                    .addComponent(fieldGender, 0, 365, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(member_id)
                                    .addComponent(gymTime, 0, 365, Short.MAX_VALUE)
                                    .addComponent(jLabel12)
                                    .addComponent(bayaran)
                                    .addComponent(jLabel11)
                                    .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSimpanData)
                                .addGap(39, 39, 39)
                                .addComponent(btnResetData)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gymTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNo_hp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(member_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpanData)
                    .addComponent(btnResetData))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  
    /**
     * Metode untuk menghasilkan ID unik berdasarkan nilai unique_id.
     * Jika unique_id sudah melebihi 9999, akan dilemparkan RuntimeException.
     * @return String representasi ID unik dengan format 4 digit angka
     */
    private synchronized String uniqueIdGen(){
        if (unique_id > 9999) {
            throw new RuntimeException("ID Sudah melebihi kapasitas");
        }
        return String.format("%04d", unique_id);
    }
    
    /**
     * Metode untuk membaca ID terakhir yang digunakan dari file.
     * Jika file tidak ditemukan, akan menampilkan pesan kesalahan dan mengembalikan nilai default 1001.
     * @return ID terakhir yang dibaca dari file atau 1001 jika gagal membaca
     */
    private int readLastUsedID(){
        File file = new File(ID_FILE_PATH);
        if (!file.exists()) {
            JOptionPane.showMessageDialog(this, "File Tidak Ada: " + ID_FILE_PATH, "Error", JOptionPane.ERROR_MESSAGE);
            return 1001;
        }
        
        try(BufferedReader reader = new BufferedReader(new FileReader(ID_FILE_PATH))){
            String lastID = reader.readLine();
            return lastID != null ? Integer.parseInt(lastID) : 1001;
        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "File Tidak Ditemukan " + ID_FILE_PATH, "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
            return 1001;
        } catch (IOException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error reading ID from file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
            return 1001;
        }
        
    }
    
    /**
     * Metode untuk menulis ID terakhir yang digunakan ke file.
     * @param id ID terakhir yang akan ditulis ke file
     */
    private void writeLastUsedID(int id){
        try(BufferedWriter writer = new BufferedWriter(new FileWriter(ID_FILE_PATH))){
            writer.write(Integer.toString(id));
        }catch(IOException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error writing ID to file", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * Metode untuk menampilkan ID unik saat ini pada komponen member_id.
     */
    private void displayUniqueId() {
        member_id.setText(uniqueIdGen());
    }    
    
    /**
     * Metode untuk mereset form dengan menghapus semua input yang dimasukkan oleh pengguna.
     */
    @Override
    public void resetForm(){
        fieldName.setText("");
        fieldNo_hp.setText("");
        fieldEmail.setText("");
        fieldGender.setSelectedItem("Choose:");
        gymTime.setSelectedItem("Select Package:");
        bayaran.setText("");
        displayUniqueId();
        jDate.getDateFormatString();
    }        
    
    // Metode-metode lainnya yang digunakan untuk meng-handle event dan validasi data
    
    private void fieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNameActionPerformed

    /**
     * Metode yang dipanggil ketika tombol Simpan Data ditekan.
     * Memvalidasi input dan menyimpan data member baru ke database.
     * Menampilkan pesan kesalahan jika input tidak valid.
     * @param evt ActionEvent yang dipicu oleh tombol Simpan Data
     */
    private void btnSimpanDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanDataActionPerformed
        // TODO add your handling code here:
        String Tgl_lahir;
        
        String name = fieldName.getText();
        String noHP = fieldNo_hp.getText();
        String email = fieldEmail.getText();
        String gender = fieldGender.getSelectedItem().toString();
        String timeGym = gymTime.getSelectedItem().toString();
        String member_no = member_id.getText();
        String bayar = bayaran.getText();
        
        if(!name.isEmpty()){
            if(!noHP.isEmpty() && noHP.matches("\\d+")){
                if(!email.isEmpty() && email.contains("@gmail.com")){
                    if(!"Choose:".equalsIgnoreCase(gender)){
                        if(!"Select Package:".equalsIgnoreCase(timeGym)){
                            if(!member_no.isEmpty()){
                                if(jDate.getDate() != null) {
                                    if(!bayar.isEmpty()) {
                                        try{
                                            if (connect == null || connect.isClosed()) {
                                                connect = Koneksi.getConnection();
                                            }
                                            String pattern = "dd-MMMM-yyyy";
                                            SimpleDateFormat format = new SimpleDateFormat(pattern);
                                            Tgl_lahir = String.valueOf(format.format(jDate.getDate()));
                                            String sql = "INSERT INTO tb_member (nama, no_hp, email, gender, gym_time, id_member, tgl_lahir, bayaran) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
                                            try(PreparedStatement p = connect.prepareStatement(sql)){
                                                p.setString(1, name);
                                                p.setString(2, noHP);
                                                p.setString(3, email);
                                                p.setString(4, gender);
                                                p.setString(5, timeGym);
                                                p.setString(6, member_no);
                                                p.setString(7, Tgl_lahir);
                                                p.setString(8, bayar);
                                                int telahTerisi = p.executeUpdate();
                                                if(telahTerisi > 0){
                                                    JOptionPane.showMessageDialog(this, "Member Baru Sukses Ditambahkan!");     
                                                    unique_id++;
                                                    writeLastUsedID(unique_id);
                                                }
                                            }
                                            resetForm();
                                        } catch(SQLException e) {
                                            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                                        }
                                    } else {
                                        JOptionPane.showMessageDialog(new JFrame(), "Tolong Masukan Jumlah Pembayaran", null, JOptionPane.ERROR_MESSAGE);
                                    }
                                } else {
                                    JOptionPane.showMessageDialog(new JFrame(), "Tolong Masukan Tanggal Lahir Member", null, JOptionPane.ERROR_MESSAGE);
                                }
                            } else {
                                JOptionPane.showMessageDialog(new JFrame(), "Ada Error Pada ID Member", null, JOptionPane.ERROR_MESSAGE);
                            }
                        } else {
                            JOptionPane.showMessageDialog(new JFrame(), "Tolong Pilih Paket Untuk Member", null, JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(new JFrame(), "Tolong Pilih Gender Member", null, JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(new JFrame(), "Tolong Masukan Email Member", null, JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(new JFrame(), "Tolong Masukan Nomor Handphone Member", null, JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(new JFrame(), "Tolong Masukan Nama Member", null, JOptionPane.ERROR_MESSAGE);
        }                  
    }//GEN-LAST:event_btnSimpanDataActionPerformed

    private void member_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_member_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_member_idActionPerformed

    /**
     * Metode yang dipanggil ketika tombol Reset Data ditekan.
     * Memanggil metode resetForm() untuk mengosongkan form.
     * @param evt ActionEvent yang dipicu oleh tombol Reset Data
     */
    private void btnResetDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetDataActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_btnResetDataActionPerformed

    /**
     * Metode yang dipanggil ketika pilihan waktu gym diubah.
     * Mengatur jumlah bayaran berdasarkan paket yang dipilih.
     * @param evt ActionEvent yang dipicu oleh perubahan pilihan di JComboBox gymTime
     */
    private void gymTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gymTimeActionPerformed
        // TODO add your handling code here:
        String selectedPack = (String) gymTime.getSelectedItem();
        
        if(selectedPack != null){
            switch(selectedPack){
                case "1 Month":
                    bayaran.setText("Rp. 100.000");
                    break;
                case "3 Month":
                    bayaran.setText("Rp. 250.000");
                    break;
                case "12 Month":
                    bayaran.setText("Rp. 750.000");
                    break;
                default:
                    bayaran.setText("");
                    break;
            }
        }
    }//GEN-LAST:event_gymTimeActionPerformed

     /**
     * Metode utama yang digunakan untuk menjalankan aplikasi ini.
     * @param args argumen baris perintah yang diberikan saat menjalankan program
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewMember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bayaran;
    private javax.swing.JButton btnResetData;
    private javax.swing.JButton btnSimpanData;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JComboBox<String> fieldGender;
    private javax.swing.JTextField fieldName;
    private javax.swing.JTextField fieldNo_hp;
    private javax.swing.JComboBox<String> gymTime;
    private com.toedter.calendar.JDateChooser jDate;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField member_id;
    // End of variables declaration//GEN-END:variables
}
