/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;


/**
 * Kelas Payment adalah GUI untuk melakukan pembayaran kepada anggota berdasarkan ID anggota.
 * Form ini memungkinkan pencarian anggota, menampilkan informasi, serta melakukan penyimpanan data pembayaran.
 * Implementasi interface Reset untuk mereset form saat diperlukan.
 * 
 * 
 * Setiap bagian dari form diinisialisasi dalam konstruktor, termasuk aksi dari tombol-tombol yang ada.
 * Terdapat fungsi untuk menyimpan pembayaran ke database, mencari anggota berdasarkan ID, serta mereset form.
 * 
 * 
 * GUI ini menggunakan komponen-komponen seperti JTextField, JButton, JLabel, dan JPanel dari Swing.
 * Komponen-komponen tersebut diatur ulang menggunakan GroupLayout untuk tampilan yang lebih rapi.
 * 
 * 
 * Koneksi database diatur melalui fungsi setCon dan getCon yang memanfaatkan objek Connection.
 * 
 * @author rifar
 */
public class Payment extends javax.swing.JFrame implements Reset{

    /**
     * Creates new form Payment
     * Menginisialisasi komponen GUI seperti label, input field, dan tombol.
     */
    public Payment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        fieldNama = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fieldNo_hp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fieldEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fieldBayaran = new javax.swing.JTextField();
        btnSimpanBayaran = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(175, 100));
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 118, 221));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PAYMENT");

        jLabel3.setText("Member ID:");

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel6.setText("Name:");

        fieldNama.setEditable(false);

        jLabel7.setText("Mobile Number:");

        fieldNo_hp.setEditable(false);

        jLabel8.setText("Email:");

        fieldEmail.setEditable(false);

        jLabel9.setText("Amount to Pay:");

        fieldBayaran.setEditable(false);

        btnSimpanBayaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save.png"))); // NOI18N
        btnSimpanBayaran.setText("Save");
        btnSimpanBayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanBayaranActionPerformed(evt);
            }
        });

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reset.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSimpanBayaran)
                                .addGap(18, 18, 18)
                                .addComponent(btnReset))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel9)
                                .addComponent(jLabel8)
                                .addComponent(jLabel6)
                                .addComponent(fieldNama, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addComponent(fieldNo_hp)
                                .addComponent(fieldEmail)
                                .addComponent(fieldBayaran)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnSearch))))))
                .addContainerGap(584, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldNo_hp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldBayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpanBayaran)
                    .addComponent(btnReset))
                .addGap(0, 129, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    Connection connect = null;
    
    /**
     * Fungsi untuk mengatur koneksi ke database.
     * @param connect objek Connection yang digunakan untuk mengakses database.
     */
    public void setCon(Connection connect){
        this.connect = connect;
    }
    
    /**
     * Fungsi untuk mendapatkan koneksi database yang sedang digunakan.
     * @return objek Connection saat ini yang terhubung ke database.
     */
    public Connection getCon(){
        return connect;
    }
    
    /**
     * Implementasi dari interface Reset.
     * Mengatur ulang semua input field pada form menjadi kosong.
     */
    @Override
    public void resetForm(){
        searchField.setText("");
        fieldNama.setText("");
        fieldNo_hp.setText("");
        fieldEmail.setText("");
        fieldBayaran.setText("");
    }
    
    /**
     * Aksi yang dilakukan saat tombol Simpan dibuat pada form.
     * Mencoba menyimpan data pembayaran ke database setelah melakukan validasi koneksi.
     * @param evt objek ActionEvent yang menandai aksi pengguna terhadap tombol.
     */
    private void btnSimpanBayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanBayaranActionPerformed
        // TODO add your handling code here:
        try{
            if (connect == null || connect.isClosed()) {
                connect = Koneksi.getConnection();
            }
            String sql = "INSERT INTO tb_bayaran (nama, no_hp, email, bayaran) VALUES (?, ?, ?, ?)";
            try(PreparedStatement p = connect.prepareStatement(sql)){
                p.setString(1, fieldNama.getText());
                p.setString(2, fieldNo_hp.getText());
                p.setString(3, fieldEmail.getText());
                p.setString(4, fieldBayaran.getText());
                int berhasilUpdate = p.executeUpdate();
                if(berhasilUpdate > 0){
                    JOptionPane.showMessageDialog(this, "Pembayaran Berhasil Dilakukan");
                    resetForm();
                }
            } 
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSimpanBayaranActionPerformed

    /**
     * Aksi yang dilakukan saat tombol Cari dibuat pada form.
     * Mencari anggota berdasarkan ID anggota yang dimasukkan pengguna.
     * @param evt objek ActionEvent yang menandai aksi pengguna terhadap tombol.
     */
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String memberID = searchField.getText().trim();
        
        if (memberID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tolong isi ID Member terlebih dahulu.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try{
            if (connect == null || connect.isClosed()) {
                connect = Koneksi.getConnection();
            }

            Statement stm = connect.createStatement();
            ResultSet rs = stm.executeQuery("SELECT * FROM tb_member WHERE id_member = '" + memberID + "'");
            
            if(rs.next()){
                String nama = rs.getString("nama");
                String noHP = rs.getString("no_hp");
                String email = rs.getString("email");
                String bayar = rs.getString("bayaran");
                
                fieldNama.setText(nama);
                fieldNo_hp.setText(noHP);
                fieldEmail.setText(email);
                fieldBayaran.setText(bayar);
            } else {
                JOptionPane.showMessageDialog(this, "Member Tidak Dapat Ditemukan!");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * Aksi yang dilakukan saat tombol Reset dibuat pada form.
     * Mengatur ulang form dengan memanggil fungsi resetForm().
     * @param evt objek ActionEvent yang menandai aksi pengguna terhadap tombol.
     */
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * Metode utama yang dimulai saat menjalankan aplikasi.
     * Membuat objek Payment dan menampilkannya secara visual.
     * @param args argumen baris perintah yang bisa diterima saat menjalankan aplikasi.
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSimpanBayaran;
    private javax.swing.JTextField fieldBayaran;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldNama;
    private javax.swing.JTextField fieldNo_hp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables
}
