/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * Kelas Register2Frame merupakan kelas untuk mengatur tampilan registrasi lanjutan pada aplikasi.
 * Kelas ini memungkinkan pengguna untuk memasukkan informasi pribadi seperti nama lengkap, jenis kelamin,
 * tanggal lahir, dan jenis langganan.
 * Implements Reseta untuk mereset form setelah proses registrasi selesai.
 * Menggunakan koneksi database untuk menyimpan data registrasi ke dalam tabel tb_login.
 * 
 * @author rifar
 */
public class Register2Frame extends javax.swing.JFrame implements Reseta{

    /**
     * Creates new form Register2Frame
     */
    public Register2Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonFemale = new javax.swing.JRadioButton();
        jButtonMale = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldFullName = new javax.swing.JTextField();
        jComboBoxBundling = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButtonFinish = new javax.swing.JButton();
        jDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 118, 211));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 400));

        jLabel1.setFont(new java.awt.Font("STXihei", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hello, introduce yourself");

        jLabel2.setFont(new java.awt.Font("STXihei", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gender:");

        jLabel3.setFont(new java.awt.Font("STXihei", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Full Name:");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        buttonGroup1.add(jButtonFemale);
        jButtonFemale.setFont(new java.awt.Font("STXihei", 0, 14)); // NOI18N
        jButtonFemale.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFemale.setText("Female");
        jButtonFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFemaleActionPerformed(evt);
            }
        });

        buttonGroup1.add(jButtonMale);
        jButtonMale.setFont(new java.awt.Font("STXihei", 0, 14)); // NOI18N
        jButtonMale.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMale.setText("Male");
        jButtonMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMaleActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("STXihei", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Birth Date");

        jTextFieldFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFullNameActionPerformed(evt);
            }
        });

        jComboBoxBundling.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bundle Types :", "Monthly", "Quarterly", "Yearly" }));
        jComboBoxBundling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBundlingActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("STXihei", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Choose Membership Bundle");

        jButtonFinish.setText("Finish");
        jButtonFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(598, 598, 598)
                                .addComponent(jComboBoxBundling, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(597, 597, 597)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonMale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonFemale)))
                        .addGap(0, 559, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(626, Short.MAX_VALUE)
                .addComponent(jButtonFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(624, 624, 624))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(596, 596, 596)
                        .addComponent(jTextFieldFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(597, 597, 597)
                        .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxBundling, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMale)
                    .addComponent(jButtonFemale)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonFinish)
                .addContainerGap(298, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private Connection connect = null;
    private ButtonGroup genderGroup = new ButtonGroup();
    
    /**
     * Method untuk mengatur koneksi ke database.
     * @param con Objek Connection yang akan diatur.
     */
    public void setCon(Connection con){
        connect = con;
    }
    
    /**
     * Method untuk mengatur grup tombol jenis kelamin.
     * @param genderGroup Objek ButtonGroup yang akan diatur.
     */
    public void setGender(ButtonGroup genderGroup){
        this.genderGroup = genderGroup;
    }
    
    /**
     * Method untuk mendapatkan objek koneksi ke database.
     * @return Objek Connection yang digunakan.
     */
    public Connection getCon(){
        return connect;
    }
    
    /**
     * Method untuk mendapatkan grup tombol jenis kelamin.
     * @return Objek ButtonGroup dari jenis kelamin.
     */
    public ButtonGroup getGender(){
        return genderGroup;
    }
    
    /**
     * Method untuk mengelompokkan tombol jenis kelamin menjadi satu grup.
     */
    public void groupButton() {
        genderGroup.add(jButtonMale);
        genderGroup.add(jButtonFemale);
    }
    
    /**
     * Implementasi dari method resetForm pada interface Reseta.
     * Digunakan untuk mereset nilai-nilai pada form setelah proses registrasi selesai.
     */
    @Override
    public void resetForm(){
        jTextFieldFullName.setText("");
        jDate.getDateFormatString();
        genderGroup.clearSelection();
        jComboBoxBundling.setSelectedItem("Jenis-Jenis Paket:");
    }
    
    private void jButtonMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMaleActionPerformed

    private void jTextFieldFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFullNameActionPerformed

    private void jButtonFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFemaleActionPerformed

     /**
     * Method yang dijalankan saat tombol Finish ditekan.
     * Digunakan untuk menyimpan data registrasi ke database setelah validasi.
     * @param evt Objek ActionEvent dari tombol Finish.
     */
    private void jButtonFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinishActionPerformed
        // TODO add your handling code here:
        String bundle = jComboBoxBundling.getSelectedItem().toString();
        String Tgl_lahir;

        if(jTextFieldFullName.getText().length() > 0){
            if(jDate.getDate() != null){
                if(!"Jenis-Jenis Paket:".equals(bundle)){
                    if(jButtonMale.isSelected() || jButtonFemale.isSelected()){
                        try{
                            if (connect == null || connect.isClosed()) {
                                connect = Koneksi.getConnection();
                            }
                            String pattern = "dd-MMMM-yyyy";
                            SimpleDateFormat format = new SimpleDateFormat(pattern);
                            Tgl_lahir = String.valueOf(format.format(jDate.getDate()));
                            String register2 = "UPDATE tb_login SET nama_panjang = ?, tanggal_lahir = ?, gender = ?, paket = ? WHERE no = (SELECT MAX(no) FROM tb_login)";
                            try(PreparedStatement p = connect.prepareStatement(register2)){
                                p.setString(1, jTextFieldFullName.getText());
                                p.setString(2, Tgl_lahir);
                                p.setString(3, jButtonMale.isSelected() ? "Male" : "Female");
                                p.setString(4, bundle);
                                p.executeUpdate();
                            }
                            setVisible(false);
                            new TampilanAwal().setVisible(true);
                            resetForm();
                        } catch(SQLException e) {
                            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(new JFrame(), "Tolong Pilih Kelamin Anda", "Invalid Gender", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                } else {
                    JOptionPane.showMessageDialog(new JFrame(), "Tolong Pilih Subcription Anda", "Invalid Subscription", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            } else {
                JOptionPane.showMessageDialog(new JFrame(), "Tolong Masukan Tanggal Lahir Anda", "Invalid Age", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } else {
            JOptionPane.showMessageDialog(new JFrame(), "Tolong Masukan Nama Panjang Anda", "Invalid Name", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
    }//GEN-LAST:event_jButtonFinishActionPerformed

    private void jComboBoxBundlingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBundlingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBundlingActionPerformed

    /**
     * Method utama untuk menjalankan aplikasi.
     * @param args Argumen baris perintah yang diberikan saat menjalankan aplikasi.
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register2Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton jButtonFemale;
    private javax.swing.JButton jButtonFinish;
    private javax.swing.JRadioButton jButtonMale;
    private javax.swing.JComboBox<String> jComboBoxBundling;
    private com.toedter.calendar.JDateChooser jDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldFullName;
    // End of variables declaration//GEN-END:variables
}
