/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

/**
 *
 * @author rifar
 */

/**
 * Kelas TampilanAwal adalah kelas utama untuk tampilan awal aplikasi.
 * Ini merupakan form utama yang menampilkan logo dan tombol untuk login dan registrasi.
 * Ketika tombol login atau registrasi ditekan, form ini akan ditutup dan form 
 * yang sesuai (LoginFrame atau RegisterFrame) akan ditampilkan.
 */
public class TampilanAwal extends javax.swing.JFrame {

    /**
     * Creates new form TampilanAwal
     */
    public TampilanAwal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonRegisterAwal = new javax.swing.JButton();
        jButtonLoginAwal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("dasdas");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 118, 221));
        jPanel2.setPreferredSize(new java.awt.Dimension(1366, 7688));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Gymshark-Antiguo-Logo-removebg-preview-fotor-2024053111928.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 390, 370));

        jButtonRegisterAwal.setBackground(new java.awt.Color(253, 126, 0));
        jButtonRegisterAwal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonRegisterAwal.setText("Register");
        jButtonRegisterAwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterAwalActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonRegisterAwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 190, 30));

        jButtonLoginAwal.setBackground(new java.awt.Color(242, 242, 242));
        jButtonLoginAwal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonLoginAwal.setText("Login");
        jButtonLoginAwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginAwalActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonLoginAwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 500, 190, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metode yang dipanggil ketika tombol "Register" ditekan.
     * Menghapus frame ini dan menampilkan RegisterFrame baru.
     *
     * @param evt Event aksi yang terjadi (dalam hal ini, tombol ditekan).
     */
    private void jButtonRegisterAwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterAwalActionPerformed
        // TODO add your handling code here:
        this.dispose();// Menutup frame saat ini
        new RegisterFrame().setVisible(true);// Menampilkan RegisterFrame
    }//GEN-LAST:event_jButtonRegisterAwalActionPerformed

    /**
     * Metode yang dipanggil ketika tombol "Login" ditekan.
     * Menghapus frame ini dan menampilkan LoginFrame baru.
     *
     * @param evt Event aksi yang terjadi (dalam hal ini, tombol ditekan).
     */
    private void jButtonLoginAwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginAwalActionPerformed
        // TODO add your handling code here:
        this.dispose();// Menutup frame saat ini
        new LoginFrame().setVisible(true);// Menampilkan LoginFrame
    }//GEN-LAST:event_jButtonLoginAwalActionPerformed

    /**
     * Metode main untuk menjalankan aplikasi. Membuat objek TampilanAwal dan
     * menampilkannya sebagai form utama.
     *
     * @param args Argumen baris perintah yang diteruskan ke aplikasi.
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TampilanAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TampilanAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TampilanAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampilanAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TampilanAwal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLoginAwal;
    private javax.swing.JButton jButtonRegisterAwal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
